-- liquibase formatted sql

-- changeset EvgenyL:1
CREATE TABLE dog
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR,
    age           INTEGER,
    breed         VARCHAR
);

CREATE TABLE cat
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR,
    age           INTEGER,
    breed         VARCHAR
);

CREATE TABLE person_dog
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id       BIGINT,
    first_name    VARCHAR,
    last_name     VARCHAR,
    phone         VARCHAR,
    dog_id        BIGINT REFERENCES dog (id)
);

CREATE TABLE person_cat
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id       BIGINT,
    first_name    VARCHAR,
    last_name     VARCHAR,
    phone         VARCHAR,
    cat_id        BIGINT REFERENCES cat (id)
);

CREATE TABLE dog_report
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_dog_id   BIGINT REFERENCES person_dog (id),
    diet            TEXT,
    condition       TEXT,
    new_habits      BOOLEAN,
    old_habits      BOOLEAN,
    report_date     DATE,
    file_id         TEXT
);

CREATE TABLE cat_report
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id         BIGINT,
    person_cat_id   BIGSERIAL REFERENCES person_cat (id),
    diet            TEXT,
    condition       TEXT,
    new_habits      BOOLEAN,
    old_habits      BOOLEAN,
    report_date     DATE,
    file_id         TEXT
);

CREATE TABLE context
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id         BIGINT,
    type            VARCHAR,
    add_days        VARCHAR,
    test_off        BOOLEAN,
    person_dog_id   BIGINT REFERENCES person_dog (id),
    person_cat_id   BIGINT REFERENCES person_cat (id)
);

-- changeset EvgenyL:2
ALTER TABLE cat_report DROP COLUMN chat_id;






